---
title: "Project 2"
author: "Sigrid Leithe, Jakob Martinussen, Marte Saghagen"
date: "October, 2017"
output: #3rd letter indentation hierarchy
#  beamer_presentation:
###    incremental: true # or >* for one at a time
#  slidy_presentation:
#    font_adjustment: +1  
#  prettydoc::html_pretty:
#    theme: architect
#    highlight: github
   pdf_document:
    toc: true
    toc_depth: 2
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,tidy = FALSE, message = FALSE, warning = FALSE)
# Cache code chunks
knitr::opts_chunk$set(cache=TRUE)

library(ggplot2, quietly = TRUE, warn.conflicts = FALSE)
library(car, quietly = TRUE, warn.conflicts = FALSE)
library(GGally, quietly = TRUE, warn.conflicts = FALSE)
library(reshape2,quietly = TRUE, warn.conflicts = FALSE)
library(cowplot,quietly = TRUE, warn.conflicts = FALSE)
library(ggthemes,quietly = TRUE, warn.conflicts = FALSE)
```


```{r child = '01-Task_1a.Rmd'}
```

```{r child = '02-Task_1b.Rmd'}
```

```{r child = '03-Task_1c.Rmd'}
```

```{r child = '04-Task_1d.Rmd'}
```

```{r setup2, include=FALSE}
knitr::opts_chunk$set(tidy = TRUE)
```

```{r child = '05-Task_2a.Rmd'}
```

```{r child = '06-Task_2b.Rmd'}
```

```{r child = '07-Task_2c.Rmd'}
```

```{r child = '08-Task_2d.Rmd'}
```

```{r child = '09-Appendix.Rmd'}
```